- name: Front container
  docker_container:
    name: front
    image: callyie/devopsproject:front
    state: started
    pull: yes
    networks:
      - name: app-network
    ports:
      - "8080:8080"


