- name: App container
  docker_container:
    name: backend
    image: callyie/devopsproject:simple-api
    state: started
    pull: yes
    networks:
      - name: app-network
    ports:
      - 8080:8080

    env:
      SPRING_DATASOURCE_PASSWORD: "{{ db_password }}"
      SPRING_DATASOURCE_USER: "{{ db_user }}"
      SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/db